name: Debug Windows

on:
  workflow_dispatch:
  pull_request:

jobs:
  debug:
    name: Windows Debug
    runs-on: windows-latest
    timeout-minutes: 30

    env:
      CI_WINDOWS: true

    steps:
      - name: Checkout PyVista
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Set up headless display
        uses: pyvista/setup-headless-display-action@5bc8de3bc71fcda7a96439571287a554901541a0

      - name: Install tox-uv
        run: pip install tox-uv

      - name: Core Testing
        env:
          TOX_OVERRIDE: |
            testenv.py3.14-core.commands_pre[0]=python -m pip install --extra-index-url https://wheels.vtk.org vtk --pre --no-cache
        run: tox run -e py3.14-core -- -k test_init_cell_array_from_regular_cells -vv -s
